export const TEMPLATE_DATA = {
  meta_moneda: { locale: 'es-CL', currency: 'CLP' },
  resumen: {
    idea: '<p>Servicio de suscripción para entrega semanal de productos personalizados con enfoque en conveniencia y calidad en Chile.</p>',
    puntos_fuertes: [
      'Demanda creciente',
      'Diferenciación por personalización',
      'Operación escalable',
      'Recurrencia (suscripción)',
      'Ticket promedio atractivo',
      'Marca con propósito',
    ],
    alertas: [
      'CAC inicial alto',
      'Dependencia de logística',
      'Rotación de inventario',
      'Estacionalidad',
      'Competencia con grandes',
      'Margen sensible a costos',
    ],
  },
  veredicto: {
    nivel: 'Alta',
    conclusion: 'Oportunidad sólida con ejecución disciplinada.',
    razones_clave: [
      'Problema claro y recurrente',
      'Oferta diferenciable',
      'Potencial de retención',
      'Escalabilidad por zonas',
      'Monetización flexible',
      'Data-driven growth',
    ],
    condiciones_para_exito: [
      'Control de costos',
      'Entrega confiable',
      'Estrategia de retención',
      'Alianzas clave',
      'Optimización de CAC',
      'Sistema de calidad',
    ],
  },
  clientes: {
    segmentos: [
      {
        nombre: 'Profesionales ocupados',
        edad_rango: '25–40',
        nivel_ingreso: 'Medio–Alto',
        necesidades: [
          'Ahorro de tiempo',
          'Calidad consistente',
          'Entrega puntual',
          'Personalización',
        ],
        dolores: ['Falta de tiempo', 'Opciones limitadas', 'Mala experiencia de entrega'],
      },
      {
        nombre: 'Familias jóvenes',
        edad_rango: '28–45',
        nivel_ingreso: 'Medio',
        necesidades: ['Conveniencia', 'Variedad', 'Precio predecible', 'Planificación'],
        dolores: ['Compras frecuentes', 'Desperdicio', 'Falta de organización'],
      },
      {
        nombre: 'Entusiastas de bienestar',
        edad_rango: '20–38',
        nivel_ingreso: 'Medio–Alto',
        necesidades: ['Opciones saludables', 'Ingredientes claros', 'Sustentabilidad'],
        dolores: ['Etiquetas confusas', 'Pocas opciones', 'Inconsistencia'],
      },
      {
        nombre: 'Empresas pequeñas',
        edad_rango: '—',
        nivel_ingreso: '—',
        necesidades: ['Beneficios', 'Facturación', 'Entrega a oficinas'],
        dolores: ['Gestión manual', 'Proveedores informales'],
      },
    ],
    tamaño_mercado: {
      metodo: 'TAM/SAM/SOM (supuestos conservadores)',
      estimacion_clientes: {
        min: 12000,
        max: 36000,
        supuesto_clave: 'Conversión por comunas + densidad (RM y regiones)',
      },
      disposicion_pagar: { rango: { min: 17990, max: 39990 } },
    },
    personas_ejemplo: [
      { nombre: 'Camila', descripcion: 'Analista, busca conveniencia y personalización.' },
      {
        nombre: 'Matías',
        descripcion: 'Papá primerizo, quiere previsibilidad y ahorro de tiempo.',
      },
    ],
  },
  escenario_competitivo: {
    competidores_directos: [
      {
        nombre: 'Competidor A',
        propuesta: 'Entrega rápida con catálogo estándar en Santiago.',
        precio_relativo: 'Similar',
        fortalezas: ['Rapidez', 'Cobertura', 'App madura'],
        debilidades: ['Poca personalización', 'Atención impersonal', 'Calidad variable'],
      },
      {
        nombre: 'Competidor B',
        propuesta: 'Productos premium con suscripción mensual.',
        precio_relativo: 'Más alto',
        fortalezas: ['Marca', 'Calidad', 'Experiencia'],
        debilidades: ['Alto costo', 'Menor flexibilidad', 'Proceso lento'],
      },
      {
        nombre: 'Competidor C',
        propuesta: 'Marketplace de opciones locales (RM y regiones).',
        precio_relativo: 'Más bajo',
        fortalezas: ['Variedad', 'Precio', 'Oferta local'],
        debilidades: ['Inconsistencia', 'Sin estandarización', 'Logística irregular'],
      },
    ],
    competidores_indirectos: [
      { tipo: 'DIY', sustituto_de: 'Suscripción', riesgo: 'Medio' },
      { tipo: 'Retail', sustituto_de: 'Entrega', riesgo: 'Alto' },
      { tipo: 'Convenience stores', sustituto_de: 'Compra rápida', riesgo: 'Medio' },
      { tipo: 'Apps de delivery', sustituto_de: 'Solución inmediata', riesgo: 'Alto' },
      { tipo: 'Clubes/planes', sustituto_de: 'Beneficios', riesgo: 'Bajo' },
    ],
    oportunidades_diferenciacion: [
      'Personalización real',
      'Garantía de calidad',
      'Suscripción flexible',
      'Contenido/educación',
      'Programa de lealtad',
      'Atención premium',
    ],
    barreras_entrada: [
      'Logística operativa',
      'Estandarización de calidad',
      'Capital de trabajo',
      'Alianzas con proveedores',
      'Adquisición de clientes',
      'Brand trust',
    ],
  },
  ubicacion_o_canal: {
    recomendacion: { tipo: 'hibrido', zona_o_plataforma: 'Santiago (RM) + expansión por regiones' },
    justificacion: ['Alta densidad', 'Poder adquisitivo', 'Logística viable', 'Recurrencia'],
    factores_exito: ['Tiempo de entrega', 'Control de merma', 'Rutas optimizadas', 'CSAT alto'],
    opciones_alternativas: ['Valparaíso/Viña', 'Concepción', 'Marketplace propio', 'Alianzas B2B'],
  },
  identidad_imagen: {
    propuesta_valor:
      '<p><strong>Entrega personalizada</strong> y confiable con calidad consistente, sin fricción.</p>',
    promesa_marca: '<p>“Haz más con tu tiempo. Nosotros resolvemos lo recurrente.”</p>',
    tono_y_estilo: ['Cercano', 'Confiable', 'Moderno', 'Claro', 'Práctico', 'Premium accesible'],
    diferenciadores_clave: [
      'Personalización',
      'Calidad consistente',
      'Suscripción flexible',
      'Soporte humano',
      'Transparencia',
      'Data & mejoras',
    ],
  },
  finanzas: {
    inversion_inicial: {
      total: 12500000,
      rubro: [
        { concepto: 'Equipo inicial', amount: 4500000 },
        { concepto: 'Marca y empaque', amount: 1800000 },
        { concepto: 'Plataforma', amount: 3000000 },
        { concepto: 'Marketing lanzamiento', amount: 1700000 },
        { concepto: 'Permisos/legales', amount: 1500000 },
      ],
    },
    costos_fijos_mensuales: [
      { concepto: 'Renta', amount: 750000 },
      { concepto: 'Nómina', amount: 2800000 },
      { concepto: 'Servicios', amount: 220000 },
      { concepto: 'Marketing', amount: 650000 },
      { concepto: 'Software', amount: 120000 },
      { concepto: 'Logística base', amount: 480000 },
    ],
    volumen_mensual_estimado: { min: 160, max: 520 },
    punto_equilibrio: {
      unidades: 240,
      ventas: 9600000,
      formula: 'Costos fijos / (Precio promedio - Costo variable)',
    },
    margen_esperado: { 'operativo_%': 0.2 },
  },
  riesgos_y_mitigantes: [
    {
      riesgo: 'Sobrecosto logístico',
      probabilidad: 'Media',
      impacto: 'Alto',
      mitigacion: 'Rutas por densidad + acuerdos con proveedores + ventanas de entrega.',
    },
    {
      riesgo: 'CAC elevado',
      probabilidad: 'Alta',
      impacto: 'Alto',
      mitigacion: 'Optimización de canales + referrals + ofertas por cohortes.',
    },
    {
      riesgo: 'Rotación/inventario',
      probabilidad: 'Media',
      impacto: 'Medio',
      mitigacion: 'Forecast por suscripción + compras just-in-time + bundles.',
    },
    {
      riesgo: 'Churn por calidad',
      probabilidad: 'Media',
      impacto: 'Alto',
      mitigacion: 'QA, SLAs, feedback loop y compensación controlada.',
    },
    {
      riesgo: 'Competencia reacciona',
      probabilidad: 'Media',
      impacto: 'Medio',
      mitigacion: 'Diferenciación por personalización + comunidad + marca.',
    },
    {
      riesgo: 'Capacidad operativa',
      probabilidad: 'Baja',
      impacto: 'Medio',
      mitigacion: 'Crecimiento por comunas + procesos + capacitación.',
    },
  ],
  kpis_sugeridos: [
    { nombre: 'CAC', periodicidad: 'Mensual', meta: '≤ 18000' },
    { nombre: 'Retención', periodicidad: 'Mensual', meta: '≥ 70%' },
    { nombre: 'Margen operativo', periodicidad: 'Mensual', meta: '≥ 20%' },
    { nombre: 'NPS', periodicidad: 'Mensual', meta: '≥ 50' },
    { nombre: 'Tiempo de entrega', periodicidad: 'Semanal', meta: '≤ 45' },
    { nombre: 'Churn', periodicidad: 'Mensual', meta: '≤ 6%' },
  ],
};
